[package]
name = "schnorr-nizk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand_core = {version = "0.5", features = ["getrandom"]}
curve25519-dalek = "2"
sha2 = "0.8.1"
